/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Card = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'position' : IDL.Tuple(IDL.Int, IDL.Int),
});
export const BoardState = IDL.Record({
  'staffCards' : IDL.Vec(Card),
  'courseCards' : IDL.Vec(Card),
});

export const idlService = IDL.Service({
  'getAllBoardStates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, BoardState))],
      ['query'],
    ),
  'getBoardState' : IDL.Func([IDL.Text], [BoardState], ['query']),
  'updateBoardState' : IDL.Func([IDL.Text, BoardState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Card = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'position' : IDL.Tuple(IDL.Int, IDL.Int),
  });
  const BoardState = IDL.Record({
    'staffCards' : IDL.Vec(Card),
    'courseCards' : IDL.Vec(Card),
  });
  
  return IDL.Service({
    'getAllBoardStates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, BoardState))],
        ['query'],
      ),
    'getBoardState' : IDL.Func([IDL.Text], [BoardState], ['query']),
    'updateBoardState' : IDL.Func([IDL.Text, BoardState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };